**NUMPY**


In [ ]:
%pip install numpy

In [ ]:
import numpy as np
   

In [ ]:
lst=list(range(1,25)) 
arr=np.array(lst)
print(type(arr))
print(type(lst))

<class 'numpy.ndarray'>
<class 'list'>


In [ ]:
#print list
lst=list(range(1,25))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [ ]:
#creating numpy array
arr  =np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
#arange() -- used to create array
arr = np.arange(1,25)
arr  #single dimensional array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
#2D array
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#creating 2d array
arr=np.array([[11,2,3],[4,5,6]])
arr

array([[11,  2,  3],
       [ 4,  5,  6]])

In [ ]:
#creating 3d array:2blocks,3rows,3column
arr=np.array([[[1,2,3],[4,5,6],[45,66,89]],[[7,8,9],[10,11,12],[75,79,96]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [45, 66, 89]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [75, 79, 96]]])

In [ ]:
# ones means it will print the 3row and 4 column and write 1
arr=np.ones((3,4))
arr 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#linspace means 1 to 10 is range and 5 is the equal distance btw them
arr=np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
#reshape means convert into 1d to 2 d
arr=np.linspace(1,10,5).reshape(5,1)
arr

array([[ 1.  ],
       [ 3.25],
       [ 5.5 ],
       [ 7.75],
       [10.  ]])

In [ ]:
#convert 1d-- 2d

arr=np.arange(0,30).reshape(2,15,1)
arr

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14]],

       [[15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29]]])

In [ ]:
arr.shape   # tell about the dimension of array

(2, 15)

In [ ]:
arr=np.arange(1,25).reshape(1,4,6)  #1d--3d(1blocks,4row,6column)
arr

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]])

In [ ]:
#random initialization
arr=np.random.randint(1,5,9)   #random variable from 1 to 5 and 9 elements
arr

array([3, 3, 2, 1, 4, 2, 2, 3, 4])

In [ ]:
arr=np.random.randint(1,5,(3,3,3))  #1d--3d (3,3,3 block,row,column)
arr

array([[[2, 2, 1],
        [2, 4, 4],
        [4, 3, 4]],

       [[4, 2, 4],
        [2, 2, 2],
        [1, 3, 3]],

       [[3, 4, 2],
        [3, 4, 4],
        [3, 3, 2]]])

In [ ]:
arr= np.random.random(15)    #15 elements,0-1 range
arr

array([0.66698507, 0.38073616, 0.70893486, 0.15718769, 0.412677  ,
       0.68420317, 0.05487769, 0.98365942, 0.04405087, 0.66393346,
       0.42322718, 0.1204979 , 0.49652054, 0.12612393, 0.69160486])

In [ ]:
arr=np.random.random((2,5))
arr                      #1d convert to 2d

array([[0.7744836 , 0.5902944 , 0.22002863, 0.43463005, 0.4545573 ],
       [0.64832698, 0.71902714, 0.51889231, 0.09037767, 0.38155276]])

In [ ]:
arr= np.random.randint(10)  #it pick only one random number
arr

3

In [ ]:
#tell about type of array
arr.dtype
arr.ndim

1

In [ ]:
#convert type of array
arr=np.array([1,2,3,4],dtype="int")
arr.dtype

dtype('int32')

In [ ]:
#tell about dimension of array
arr.ndim

1

In [ ]:
arr.size   #tell about the amount of element in an array

4

In [ ]:
arr.shape     #tell about the shape: how many row and column

(4,)

In [ ]:
#convert 3d and 2d into 1d
arr=np.array([[[1,2,3],[4,5,6],[45,66,89]],[[7,8,9],[10,11,12],[75,79,96]]])
arr.flatten()

array([ 1,  2,  3,  4,  5,  6, 45, 66, 89,  7,  8,  9, 10, 11, 12, 75, 79,
       96])

In [ ]:
##convert 3d and 2d into 1d
arr.ravel()

array([ 1,  2,  3,  4,  5,  6, 45, 66, 89,  7,  8,  9, 10, 11, 12, 75, 79,
       96])

In [ ]:
l=[1,2,3,4,5]
arr=np.array(l)
arr
arr.shape
arr.T.shape

(5,)

In [ ]:
arr=np.random.random((2,5))
arr
print(arr.shape)
arr.T.shape  # transpose the shape

(2, 5)


(5, 2)

In [ ]:
arr.T.shape
arr.T

array([[0.80045579, 0.53388309],
       [0.99385302, 0.41617025],
       [0.89304539, 0.96580413],
       [0.25404616, 0.77619204],
       [0.50535853, 0.38422145]])